summary: A command-line tool to help you insert the correct compiler options when compiling objects and/or linking libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-linux-s390x/releases/download/2024.08.15/pkg-config-0.29.2-linux-s390x.tar.xz
bin-sha: b08b1be611f33b536aa8f00c06d2053fd78eab14b37f90f40dbf221ef9143244
